# Form implementation generated from reading ui file 'Maint_Maint_menu.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Maint_maint_menu(object):
    def setupUi(self, Maint_maint_menu):
        Maint_maint_menu.setObjectName("Maint_maint_menu")
        Maint_maint_menu.resize(800, 599)
        self.centralwidget = QtWidgets.QWidget(parent=Maint_maint_menu)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 801, 571))
        self.label.setStyleSheet("background-image: url(Maintenance.png);\n"
"background-repeat: no-repeat;\n"
"background-position: center;\n"
"background-attachment: fixed;\n"
"background-color: white; /* Fallback color */")
        self.label.setText("")
        self.label.setObjectName("label")
        Maint_maint_menu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Maint_maint_menu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        Maint_maint_menu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Maint_maint_menu)
        self.statusbar.setObjectName("statusbar")
        Maint_maint_menu.setStatusBar(self.statusbar)

        self.retranslateUi(Maint_maint_menu)
        QtCore.QMetaObject.connectSlotsByName(Maint_maint_menu)

    def retranslateUi(self, Maint_maint_menu):
        _translate = QtCore.QCoreApplication.translate
        Maint_maint_menu.setWindowTitle(_translate("Maint_maint_menu", "Maintenance Menu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Maint_maint_menu = QtWidgets.QMainWindow()
    ui = Ui_Maint_maint_menu()
    ui.setupUi(Maint_maint_menu)
    Maint_maint_menu.show()
    sys.exit(app.exec())
