from django.urls import path
from . import views
from . import api_views

urlpatterns = [
    path('', views.home, name='home'),
    path('healthz/', views.healthz, name='healthz'),
    path('notifications/', views.notifications_list, name='notifications_list'),
    path('notifications/unread-count/', views.notifications_unread_count,
         name='notifications_unread_count'),
    path('notifications/mark-all-read/', views.notifications_mark_all_read,
         name='notifications_mark_all_read'),
    path('notifications/<int:notification_id>/read/', views.notifications_mark_read,
         name='notifications_mark_read'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    path('forgot-password/', views.forgot_password, name='forgot_password'),
    path(
    'forgot-password/reset/',
    views.forgot_password_reset,
     name='forgot_password_reset'),
    path('change-password/', views.change_password, name='change_password'),
    path('user-roles/', views.user_roles, name='user_roles'),
    path('sso/login/', views.sso_login, name='sso_login'),
    path('sso/callback/', views.sso_callback, name='sso_callback'),
    path('po/', views.po_list, name='po_list'),
    path('po/export/', views.po_export, name='po_export'),
    path('po/new/', views.po_new, name='po_new'),
    path('po/<int:po_id>/', views.po_detail, name='po_detail'),
    path('po/<int:po_id>/edit/', views.po_edit, name='po_edit'),
    path('po/<int:po_id>/items/add/', views.po_add_item, name='po_add_item'),
    path('po/<int:po_id>/items/remove/', views.po_remove_item,
         name='po_remove_item'),
    path('po/<int:po_id>/items/receive/', views.po_receive_item,
         name='po_receive_item'),
    path('po/<int:po_id>/status/', views.po_set_status, name='po_set_status'),
    path('po/<int:po_id>/landed-cost/new/', views.po_landed_cost_new,
         name='po_landed_cost_new'),
    path('po/<int:po_id>/landed-cost/<int:lc_id>/', views.po_landed_cost_detail,
         name='po_landed_cost_detail'),
    path('blanket-po/', views.blanket_po_list, name='blanket_po_list'),
    path('blanket-po/new/', views.blanket_po_new, name='blanket_po_new'),
    path('blanket-po/<int:blanket_po_id>/', views.blanket_po_detail,
         name='blanket_po_detail'),
    path('blanket-po/<int:blanket_po_id>/release/new/',
         views.blanket_po_release_new, name='blanket_po_release_new'),
    path('blanket-po/<int:blanket_po_id>/cancel/', views.blanket_po_cancel,
         name='blanket_po_cancel'),
    path('consignment/', views.consignment_list, name='consignment_list'),
    path('consignment/new/', views.consignment_new, name='consignment_new'),
    path('consignment/<int:agreement_id>/', views.consignment_detail,
         name='consignment_detail'),
    path('consignment/<int:agreement_id>/receive/', views.consignment_receive,
         name='consignment_receive'),
    path('consignment/<int:agreement_id>/use/', views.consignment_use,
         name='consignment_use'),
    path('consignment/<int:agreement_id>/cancel/', views.consignment_cancel,
         name='consignment_cancel'),
    path('rfq/', views.rfq_list, name='rfq_list'),
    path('rfq/new/', views.rfq_new, name='rfq_new'),
    path('rfq/<int:rfq_id>/', views.rfq_detail, name='rfq_detail'),
    path('reports/', views.reports_dashboard, name='reports_dashboard'),
    # Shop Floor / OEE (P3-G)
    path('shop-floor/', views.sf_dashboard, name='sf_dashboard'),
    path('shop-floor/entry/', views.sf_entry, name='sf_entry'),
    path('shop-floor/plan/', views.sf_shift_plan, name='sf_shift_plan'),
    path('shop-floor/tv/', views.sf_tv, name='sf_tv'),
    path('wo/', views.wo_list, name='wo_list'),
    path('wo/export/', views.wo_export, name='wo_export'),
    path('wo/new/', views.wo_new, name='wo_new'),
    path('wo/<int:wo_id>/', views.wo_detail, name='wo_detail'),
    path('wo/<int:wo_id>/edit/', views.wo_edit, name='wo_edit'),
    path('wo/<int:wo_id>/materials/add/', views.wo_add_material,
         name='wo_add_material'),
    path('wo/<int:wo_id>/status/', views.wo_set_status, name='wo_set_status'),
    path('so/', views.so_list, name='so_list'),
    path('so/export/', views.so_export, name='so_export'),
    path('so/new/', views.so_new, name='so_new'),
    path('so/<int:so_id>/', views.so_detail, name='so_detail'),
    path('so/<int:so_id>/edit/', views.so_edit, name='so_edit'),
    path('so/<int:so_id>/items/add/', views.so_add_item, name='so_add_item'),
    path('so/<int:so_id>/items/remove/', views.so_remove_item,
         name='so_remove_item'),
    path('so/<int:so_id>/status/', views.so_set_status, name='so_set_status'),
    # EDI Integration (P4-D)
    path('edi/partners/', views.edi_partner_list, name='edi_partner_list'),
    path('edi/partners/new/', views.edi_partner_new, name='edi_partner_new'),
    path('edi/partners/<int:customer_id>/', views.edi_partner_detail,
         name='edi_partner_detail'),
    path('edi/850/upload/', views.edi_850_upload, name='edi_850_upload'),
    path('edi/855/<int:so_id>/download/', views.edi_855_download,
         name='edi_855_download'),
    path('edi/856/<int:shipment_id>/download/', views.edi_856_download,
         name='edi_856_download'),
    path('edi/810/<int:invoice_id>/download/', views.edi_810_download,
         name='edi_810_download'),
    path('edi/log/', views.edi_transaction_log_list, name='edi_transaction_log_list'),
    path('atp/', views.atp_inquiry, name='atp_inquiry'),
    path('ctp/', views.ctp_inquiry, name='ctp_inquiry'),
    path('price-lists/', views.pl_list, name='pl_list'),
    path('price-lists/new/', views.pl_new, name='pl_new'),
    path('price-lists/<int:pl_id>/', views.pl_detail, name='pl_detail'),
    path('promotions/', views.promo_list, name='promo_list'),
    path('promotions/new/', views.promo_new, name='promo_new'),
    path('promotions/<int:promo_id>/', views.promo_detail, name='promo_detail'),
    path('sampling-plans/', views.sampling_plan_list, name='sampling_plan_list'),
    path('sampling-plans/new/', views.sampling_plan_new, name='sampling_plan_new'),
    path('sampling-plans/<int:plan_id>/', views.sampling_plan_detail,
         name='sampling_plan_detail'),
    path('qa/coa/', views.coa_list, name='coa_list'),
    path('qa/coa/new/', views.coa_new, name='coa_new'),
    path('qa/coa/<int:coa_id>/', views.coa_detail, name='coa_detail'),
    path('qa/coa/<int:coa_id>/pdf/', views.coa_pdf, name='coa_pdf'),
    path('skills/', views.skill_list, name='skill_list'),
    path('skills/new/', views.skill_new, name='skill_new'),
    path('skills/requirements/', views.skill_requirements, name='skill_requirements'),
    path('skills/matrix/', views.skills_matrix_summary, name='skills_matrix_summary'),
    path('skills/employee/<int:people_id>/', views.employee_gap_detail,
         name='employee_gap_detail'),
    path('documents/', views.document_list, name='document_list'),
    path('documents/new/', views.document_new, name='document_new'),
    path('documents/<int:doc_id>/', views.document_detail, name='document_detail'),
    path('documents/<int:doc_id>/download/', views.document_download,
         name='document_download'),
    path('ess/', views.ess_home, name='ess_home'),
    path('ess/pay-stubs/', views.ess_pay_stubs, name='ess_pay_stubs'),
    path('ess/pay-stubs/<int:entry_id>/', views.ess_pay_stub_detail, name='ess_pay_stub_detail'),
    path('ess/ytd/', views.ess_ytd, name='ess_ytd'),
    path('ess/time-off/', views.ess_time_off, name='ess_time_off'),
    path('ess/reviews/', views.ess_reviews, name='ess_reviews'),
    path('ess/reviews/<int:review_id>/', views.ess_review_detail, name='ess_review_detail'),
    path('ess/training/', views.ess_trainings, name='ess_trainings'),
    path('ess/training/<int:training_id>/', views.ess_training_detail, name='ess_training_detail'),
    path('ess/profile/', views.ess_profile, name='ess_profile'),
    path('people/', views.people_list, name='people_list'),
    path('people/new/', views.people_new, name='people_new'),
    path('people/<int:person_id>/', views.people_detail, name='people_detail'),
    path('people/<int:person_id>/edit/', views.people_edit, name='people_edit'),
    path('time-off/', views.time_off_list, name='time_off_list'),
    path('time-off/new/', views.time_off_new, name='time_off_new'),
    path('time-off/<int:req_id>/', views.time_off_detail,
         name='time_off_detail'),
    path('time-clock/', views.time_clock_status, name='time_clock_status'),
    path('time-clock/hours/', views.time_clock_hours, name='time_clock_hours'),
    path('time-clock/attendance/', views.time_clock_attendance,
         name='time_clock_attendance'),
    path('time-clock/ot/', views.tc_ot_report, name='tc_ot_report'),
    path('time-clock/schedule/', views.tc_schedule, name='tc_schedule'),
    path('time-clock/devices/', views.tc_device_list,
         name='tc_device_list'),
    path('time-clock/devices/new/', views.tc_device_new,
         name='tc_device_new'),
    path('time-clock/devices/<int:device_id>/', views.tc_device_detail,
         name='tc_device_detail'),
    path('time-clock/devices/<int:device_id>/poll/', views.tc_device_poll,
         name='tc_device_poll'),
    path('time-clock/devices/<int:device_id>/delete/', views.tc_device_delete,
         name='tc_device_delete'),
    path('audit/', views.audit_log, name='audit_log'),
    path('audit/<str:table_name>/<int:record_id>/',
         views.audit_record, name='audit_record'),
    # Lot tracking (7A)
    path('lots/', views.lot_list, name='lot_list'),
    path('lots/new/', views.lot_new, name='lot_new'),
    path('lots/<int:lot_id>/', views.lot_detail, name='lot_detail'),
    # Routing / workcenters (7A)
    path('workcenters/', views.workcenter_list, name='workcenter_list'),
    path('workcenters/<int:wc_id>/calendar/', views.workcenter_calendar, name='workcenter_calendar'),
    path('routing/<int:product_id>/', views.routing_detail, name='routing_detail'),
    # Costing (7A)
    path('costs/<int:product_id>/', views.cost_detail, name='cost_detail'),
    path('wo/<int:wo_id>/cost/', views.wo_cost_detail, name='wo_cost_detail'),
    path('bom/', views.bom_list, name='bom_list'),
    path('bom/<int:product_id>/', views.bom_detail, name='bom_detail'),
    path('bom/<int:product_id>/explode/', views.bom_explode, name='bom_explode'),
    path('mrp/', views.mrp_home, name='mrp_home'),
    path('mrp/run/', views.mrp_run, name='mrp_run'),
    path('mrp/plan/', views.mrp_plan, name='mrp_plan'),
    path('mrp/release/', views.mrp_release, name='mrp_release'),
    path('mrp/safety-stock/', views.mrp_safety_stock, name='mrp_safety_stock'),
    # AI Demand Forecasting (P4-A)
    path('demand-forecast/', views.demand_forecast_dashboard, name='demand_forecast_dashboard'),
    path('demand-forecast/generate/', views.demand_forecast_generate,
         name='demand_forecast_generate'),
    path('inventory/', views.inventory_list, name='inventory_list'),
    path('inventory/dashboard/', views.inventory_dashboard, name='inventory_dashboard'),
    path('inventory/export/', views.inventory_export, name='inventory_export'),
    path('inventory/new/', views.inventory_new, name='inventory_new'),
    path('inventory/<int:product_id>/', views.inventory_detail,
         name='inventory_detail'),
    path('inventory/<int:product_id>/transaction/',
         views.inventory_transaction, name='inventory_transaction'),
    path('inventory/cycle-counts/', views.cc_list, name='cc_list'),
    path('inventory/cycle-counts/new/', views.cc_new, name='cc_new'),
    path('inventory/cycle-counts/<int:count_id>/', views.cc_detail, name='cc_detail'),
    path('inventory/valuation/', views.costing_valuation_list, name='costing_valuation_list'),
    path('inventory/<int:product_id>/valuation/', views.costing_product_detail,
         name='costing_product_detail'),
    path('customers/', views.customer_list, name='customer_list'),
    path('customers/new/', views.customer_new, name='customer_new'),
    path('customers/<int:customer_id>/', views.customer_detail,
         name='customer_detail'),
    path('suppliers/', views.supplier_list, name='supplier_list'),
    path('suppliers/new/', views.supplier_new, name='supplier_new'),
    path('suppliers/scorecard/', views.supplier_scorecard_list,
         name='supplier_scorecard_list'),
    path('suppliers/scorecard/<int:supplier_id>/', views.supplier_scorecard_detail,
         name='supplier_scorecard_detail'),
    path('suppliers/<int:supplier_id>/', views.supplier_detail,
         name='supplier_detail'),
    path('cs/', views.cs_ticket_list, name='cs_ticket_list'),
    path('cs/new/', views.cs_ticket_new, name='cs_ticket_new'),
    path('cs/<int:ticket_id>/', views.cs_ticket_detail,
         name='cs_ticket_detail'),
    path('cs/escalations/', views.cs_escalations, name='cs_escalations'),
    path('cs/reports/', views.cs_reports, name='cs_reports'),
    path('cs/plans/', views.cs_plans, name='cs_plans'),
    path('maint/', views.maint_dashboard, name='maint_dashboard'),
    path('maint/oee/', views.maint_oee_report, name='maint_oee_report'),
    path('maint/oee/export/', views.maint_oee_export, name='maint_oee_export'),
    path('predictive-maintenance/', views.predictive_maintenance_dashboard,
         name='predictive_maintenance_dashboard'),
    path('predictive-maintenance/sensor-reading/new/', views.sensor_reading_new,
         name='sensor_reading_new'),
    path('predictive-maintenance/sensor-threshold/', views.sensor_threshold_set,
         name='sensor_threshold_set'),
    path('maint/wo/', views.maint_wo_list, name='maint_wo_list'),
    path('maint/wo/export/', views.maint_wo_export, name='maint_wo_export'),
    path('maint/wo/<int:wo_id>/', views.maint_wo_detail, name='maint_wo_detail'),
    path('maint/equipment/', views.maint_equipment_list,
         name='maint_equipment_list'),
    path('maint/equipment/<int:eq_id>/', views.maint_equipment_detail,
         name='maint_equipment_detail'),
    path('maint/schedule/', views.maint_schedule_list,
         name='maint_schedule_list'),
    path('maint/schedule/<int:sched_id>/', views.maint_schedule_detail,
         name='maint_schedule_detail'),
    path('maint/inspections/', views.maint_inspection_list,
         name='maint_inspection_list'),
    path('maint/inspections/<int:insp_id>/', views.maint_inspection_detail,
         name='maint_inspection_detail'),
    path('maint/downtime/', views.maint_downtime_list,
         name='maint_downtime_list'),
    path('maint/downtime/<int:dt_id>/', views.maint_downtime_detail,
         name='maint_downtime_detail'),
    path('maint/parts/', views.maint_parts_list, name='maint_parts_list'),
    path('maint/parts/<int:part_id>/', views.maint_part_detail,
         name='maint_part_detail'),
    path('maint/mechanics/', views.maint_mechanics_list,
         name='maint_mechanics_list'),
    path('maint/mechanics/<int:mech_id>/', views.maint_mechanic_detail,
         name='maint_mechanic_detail'),
    path('qa/', views.qa_dashboard, name='qa_dashboard'),
    path('qa/ncr/', views.qa_ncr_list, name='qa_ncr_list'),
    path('qa/ncr/export/', views.qa_ncr_export, name='qa_ncr_export'),
    path('qa/ncr/<int:ncr_id>/', views.qa_ncr_detail, name='qa_ncr_detail'),
    path('qa/capa/', views.qa_capa_list, name='qa_capa_list'),
    path('qa/capa/<int:capa_id>/', views.qa_capa_detail, name='qa_capa_detail'),
    path('qa/audits/', views.qa_audit_list, name='qa_audit_list'),
    path('qa/audits/<int:audit_id>/', views.qa_audit_detail,
         name='qa_audit_detail'),
    path('qa/suppliers/', views.qa_supplier_list, name='qa_supplier_list'),
    path('qa/suppliers/<int:sq_id>/', views.qa_supplier_detail,
         name='qa_supplier_detail'),
    path('qa/inspections/', views.qa_inspection_list,
         name='qa_inspection_list'),
    path('qa/inspections/<int:insp_id>/', views.qa_inspection_detail,
         name='qa_inspection_detail'),
    path('qa/reports/', views.qa_reports_view, name='qa_reports'),
    path('periods/', views.periods, name='periods'),
    path('po/approvals/', views.po_approvals, name='po_approvals'),
    path('po/approvals/<int:approval_id>/approve/', views.po_approve, name='po_approve'),
    path('po/approvals/<int:approval_id>/reject/', views.po_reject, name='po_reject'),
    # Payroll
    path('payroll/', views.payroll_dashboard, name='payroll_dashboard'),
    path('payroll/pay-rates/', views.payroll_pay_rates, name='payroll_pay_rates'),
    path('payroll/deductions/', views.payroll_deductions, name='payroll_deductions'),
    path('payroll/history/', views.payroll_history, name='payroll_history'),
    path('payroll/history/export/', views.payroll_history_export,
         name='payroll_history_export'),
    path('payroll/history/<int:run_id>/', views.payroll_run_detail, name='payroll_run_detail'),
    path('payroll/stubs/<int:entry_id>/', views.payroll_stub_detail, name='payroll_stub_detail'),
    path('payroll/ytd/', views.payroll_ytd, name='payroll_ytd'),
    # Accounting dashboard
    path('acct/', views.acct_dashboard, name='acct_dashboard'),
    # Accounts Payable
    path('ap/', views.ap_list, name='ap_list'),
    path('ap/export/', views.ap_export, name='ap_export'),
    path('ap/new/', views.ap_invoice_detail, name='ap_invoice_new'),
    path('ap/<int:inv_id>/', views.ap_invoice_detail, name='ap_invoice_detail'),
    # Accounts Receivable
    path('ar/', views.ar_list, name='ar_list'),
    path('ar/export/', views.ar_export, name='ar_export'),
    path('ar/new/', views.ar_invoice_detail, name='ar_invoice_new'),
    path('ar/<int:inv_id>/', views.ar_invoice_detail, name='ar_invoice_detail'),
    # General Ledger
    path('gl/', views.gl_dashboard, name='gl_dashboard'),
    path('gl/accounts/', views.gl_accounts, name='gl_accounts'),
    path('gl/journals/', views.gl_journals, name='gl_journals'),
    path('gl/journals/new/', views.gl_journal_detail, name='gl_journal_new'),
    path('gl/journals/<int:journal_id>/', views.gl_journal_detail, name='gl_journal_detail'),
    path('gl/trial-balance/', views.gl_trial_balance, name='gl_trial_balance'),
    path('gl/income-statement/', views.gl_income_statement, name='gl_income_statement'),
    path('gl/balance-sheet/', views.gl_balance_sheet, name='gl_balance_sheet'),
    path('gl/cash-flow/', views.gl_cash_flow_statement, name='gl_cash_flow_statement'),
    # Multi-Entity (P3-F)
    path('companies/', views.company_list, name='company_list'),
    path('companies/new/', views.company_new, name='company_new'),
    path('companies/<int:company_id>/', views.company_detail, name='company_detail'),
    path('companies/<int:company_id>/assign-user/', views.company_assign_user,
         name='company_assign_user'),
    path('companies/<int:company_id>/revoke-user/<int:people_id>/',
         views.company_revoke_user, name='company_revoke_user'),
    path('intercompany/', views.intercompany_list, name='intercompany_list'),
    path('intercompany/new/', views.intercompany_new, name='intercompany_new'),
    path('consolidated-financials/', views.consolidated_financials,
         name='consolidated_financials'),
    path('fin/forecast/', views.fin_cash_forecast, name='fin_cash_forecast'),
    path('eng/', views.eng_dashboard, name='eng_dashboard'),
    path('eng/projects/', views.eng_projects, name='eng_projects'),
    path('eng/projects/new/', views.eng_project_detail, name='eng_project_new'),
    path('eng/projects/<int:project_id>/', views.eng_project_detail, name='eng_project_detail'),
    path('eng/ecrs/', views.eng_ecrs, name='eng_ecrs'),
    path('eng/ecrs/new/', views.eng_ecr_detail, name='eng_ecr_new'),
    path('eng/ecrs/<int:ecr_id>/', views.eng_ecr_detail, name='eng_ecr_detail'),
    path('eng/reports/', views.eng_reports_view, name='eng_reports'),
    path('eng/tasks/', views.eng_tasks_list, name='eng_tasks_list'),
    path('eng/tasks/<int:task_id>/', views.eng_task_detail, name='eng_task_detail'),
    path('eng/specs/', views.eng_specs_list, name='eng_specs_list'),
    path('eng/specs/<int:spec_id>/', views.eng_spec_detail, name='eng_spec_detail'),
    path('sales/', views.sales_dashboard, name='sales_dashboard'),
    path('sales/orders/', views.sales_orders_list, name='sales_orders_list'),
    path('sales/orders/new/', views.sales_order_detail, name='sales_order_new'),
    path('sales/orders/<int:so_id>/', views.sales_order_detail, name='sales_order_detail'),
    path('sales/quotes/', views.sales_quotes, name='sales_quotes'),
    path('sales/targets/', views.sales_targets, name='sales_targets'),
    path('sales/leads/', views.sales_leads_list, name='sales_leads_list'),
    path('sales/leads/<int:lead_id>/', views.sales_leads_detail, name='sales_leads_detail'),
    path('sales/contracts/', views.sales_contracts_list, name='sales_contracts_list'),
    path('sales/contracts/<int:contract_id>/', views.sales_contracts_detail, name='sales_contracts_detail'),
    path('sales/forecast/', views.sales_forecast_list, name='sales_forecast_list'),
    path('sales/forecast/<int:forecast_id>/', views.sales_forecast_detail, name='sales_forecast_detail'),
    path('sales/demand/', views.sales_demand, name='sales_demand'),
    path('sales/territories/', views.sales_territories, name='sales_territories'),
    path('sales/territories/performance/', views.sales_territory_performance,
         name='sales_territory_performance'),
    path('sales/commissions/', views.sales_commissions, name='sales_commissions'),
    path('sales/commissions/history/', views.sales_commission_history,
         name='sales_commission_history'),
    path('sales/commissions/plans/', views.sales_commission_plans,
         name='sales_commission_plans'),
    path('sales/performance/', views.sales_performance, name='sales_performance'),
    path('sales/performance/reviews/', views.sales_performance_reviews,
         name='sales_performance_reviews'),
    path('sales/performance/coaching/', views.sales_coaching, name='sales_coaching'),
    path('prod/', views.prod_dashboard, name='prod_dashboard'),
    path('prod/schedule/', views.prod_schedule, name='prod_schedule'),
    path('prod/schedule/gantt/', views.prod_schedule_gantt, name='prod_schedule_gantt'),
    path('prod/schedule/gantt/reschedule/', views.prod_schedule_gantt_reschedule,
         name='prod_schedule_gantt_reschedule'),
    path('prod/schedule/capacity/', views.capacity_planning, name='capacity_planning'),
    path('scenarios/', views.scenario_list, name='scenario_list'),
    path('scenarios/new/', views.scenario_new, name='scenario_new'),
    path('scenarios/<int:scenario_id>/', views.scenario_detail, name='scenario_detail'),
    path('scenarios/<int:scenario_id>/run/', views.scenario_run, name='scenario_run'),
    path('qa/control-plans/', views.control_plan_list, name='control_plan_list'),
    path('qa/control-plans/new/', views.control_plan_new, name='control_plan_new'),
    path('qa/control-plans/<int:plan_id>/', views.control_plan_detail, name='control_plan_detail'),
    path('qa/fmea/risk-register/', views.fmea_risk_register, name='fmea_risk_register'),
    path('gl/abc-costing/activities/', views.abc_activity_list, name='abc_activity_list'),
    path('gl/abc-costing/activities/new/', views.abc_activity_new, name='abc_activity_new'),
    path('gl/abc-costing/activities/<int:activity_id>/', views.abc_activity_detail,
         name='abc_activity_detail'),
    path('gl/abc-costing/report/', views.abc_report, name='abc_report'),
    path('gl/abc-costing/products/<int:product_id>/output/', views.abc_product_output,
         name='abc_product_output'),
    path('benefits/', views.benefits_dashboard, name='benefits_dashboard'),
    path('benefits/plans/new/', views.benefit_plan_new, name='benefit_plan_new'),
    path('benefits/plans/<int:plan_id>/', views.benefit_plan_detail, name='benefit_plan_detail'),
    path('benefits/employee/<int:people_id>/', views.employee_benefits, name='employee_benefits'),
    path('qa/compliance/templates/', views.compliance_template_list, name='compliance_template_list'),
    path('qa/compliance/templates/new/', views.compliance_template_new, name='compliance_template_new'),
    path('qa/compliance/templates/<int:template_id>/', views.compliance_template_detail,
         name='compliance_template_detail'),
    path('qa/compliance/checklists/', views.compliance_checklist_list, name='compliance_checklist_list'),
    path('qa/compliance/checklists/<int:checklist_id>/', views.compliance_checklist_detail,
         name='compliance_checklist_detail'),
    path('workforce/', views.workforce_analytics, name='workforce_analytics'),
    path('workforce/headcount-plans/new/', views.headcount_plan_new, name='headcount_plan_new'),
    path('workforce/employee/<int:people_id>/', views.employee_employment_dates,
         name='employee_employment_dates'),
    path('ats/', views.ats_dashboard, name='ats_dashboard'),
    path('ats/requisitions/', views.ats_requisition_list, name='ats_requisition_list'),
    path('ats/requisitions/new/', views.ats_requisition_new, name='ats_requisition_new'),
    path('ats/requisitions/<int:req_id>/', views.ats_requisition_detail,
         name='ats_requisition_detail'),
    path('ats/candidates/', views.ats_candidate_list, name='ats_candidate_list'),
    path('ats/candidates/new/', views.ats_candidate_new, name='ats_candidate_new'),
    path('ats/candidates/<int:candidate_id>/', views.ats_candidate_detail,
         name='ats_candidate_detail'),
    path('ats/applications/<int:app_id>/', views.ats_application_detail,
         name='ats_application_detail'),
    path('cto/products/', views.cto_product_list, name='cto_product_list'),
    path('cto/products/<int:product_id>/options/', views.cto_options, name='cto_options'),
    path('cto/configure/<int:so_item_id>/', views.cto_configure, name='cto_configure'),
    path('recipes/', views.recipe_list, name='recipe_list'),
    path('recipes/new/', views.recipe_new, name='recipe_new'),
    path('recipes/<int:recipe_id>/', views.recipe_detail, name='recipe_detail'),
    path('repetitive/', views.repetitive_schedule_list, name='repetitive_schedule_list'),
    path('repetitive/new/', views.repetitive_schedule_new, name='repetitive_schedule_new'),
    path('repetitive/<int:schedule_id>/', views.repetitive_schedule_detail,
         name='repetitive_schedule_detail'),
    path('maint/routes/', views.technician_route_list, name='technician_route_list'),
    path('maint/routes/new/', views.technician_route_new, name='technician_route_new'),
    path('maint/routes/<int:route_id>/', views.technician_route_detail,
         name='technician_route_detail'),
    path('maint/apm/', views.apm_dashboard, name='apm_dashboard'),
    path('maint/apm/criticality/', views.apm_criticality, name='apm_criticality'),
    path('maint/apm/asset/', views.apm_asset_detail, name='apm_asset_detail'),
    path('batch-records/', views.batch_record_list, name='batch_record_list'),
    path('batch-records/<int:record_id>/', views.batch_record_detail, name='batch_record_detail'),
    path('batch-records/<int:record_id>/pdf/', views.batch_record_pdf, name='batch_record_pdf'),
    path('ai-insights/', views.ai_insights_dashboard, name='ai_insights_dashboard'),
    path('prod/reports/', views.prod_reports_view, name='prod_reports_view'),
    path('prod/shipping/', views.prod_shipping_list, name='prod_shipping_list'),
    path('prod/shipping/<int:shipment_id>/', views.prod_shipping_detail, name='prod_shipping_detail'),
    path('prod/tracking/', views.prod_tracking_dashboard, name='prod_tracking_dashboard'),
    path('prod/delivery-status/', views.prod_delivery_status, name='prod_delivery_status'),
    path('prod/daily-report/', views.prod_daily_report, name='prod_daily_report'),
    path('prod/performance/', views.prod_performance_report, name='prod_performance_report'),
    path('prod/returns/new/', views.prod_returns_new, name='prod_returns_new'),
    path('prod/returns/reports/', views.prod_returns_reports, name='prod_returns_reports'),
    path('prod/returns/<int:rma_id>/', views.prod_returns_detail, name='prod_returns_detail'),
    path('prod/returns/', views.prod_returns_list, name='prod_returns_list'),
    path('wms/warehouses/', views.wms_warehouse_list, name='wms_warehouse_list'),
    path('wms/bins/', views.wms_bin_list, name='wms_bin_list'),
    path('wms/bins/new/', views.wms_bin_new, name='wms_bin_new'),
    path('wms/bins/<int:bin_id>/', views.wms_bin_detail, name='wms_bin_detail'),
    path('wms/putaway-rules/', views.wms_putaway_rule_list, name='wms_putaway_rule_list'),
    path('wms/receive/', views.wms_receive, name='wms_receive'),
    path('wms/picks/', views.wms_pick_list_list, name='wms_pick_list_list'),
    path('wms/picks/<int:pick_list_id>/', views.wms_pick_list_detail, name='wms_pick_list_detail'),
    path('wms/pack/<int:pick_list_id>/', views.wms_pack_station, name='wms_pack_station'),
    path('wms/ship/<int:pick_list_id>/', views.wms_ship_confirm, name='wms_ship_confirm'),
    path('wms/transfers/', views.wms_transfer_list, name='wms_transfer_list'),
    path('wms/transfers/new/', views.wms_transfer_new, name='wms_transfer_new'),
    path('wms/transfers/<int:transfer_id>/', views.wms_transfer_detail, name='wms_transfer_detail'),
    path('wms/waves/', views.wms_wave_list, name='wms_wave_list'),
    path('wms/waves/<int:wave_id>/', views.wms_wave_detail, name='wms_wave_detail'),
    path('wms/rfid/readers/', views.wms_rfid_reader_list, name='wms_rfid_reader_list'),
    path('wms/rfid/tags/', views.wms_rfid_tag_list, name='wms_rfid_tag_list'),
    path('wms/rfid/tags/<int:tag_id>/', views.wms_rfid_tag_detail, name='wms_rfid_tag_detail'),
    path('fin/', views.fin_dashboard, name='fin_dashboard'),
    path('fin/budgets/', views.fin_budget_list, name='fin_budget_list'),
    path('fin/budgets/<int:budget_id>/', views.fin_budget_detail, name='fin_budget_detail'),
    path('fin/audits/', views.fin_audit_list, name='fin_audit_list'),
    path('fin/audits/<int:audit_id>/', views.fin_audit_detail, name='fin_audit_detail'),
    path('fin/bank-rec/', views.fin_bank_rec_list, name='fin_bank_rec_list'),
    path('fin/bank-rec/<int:account_id>/', views.fin_bank_rec_detail, name='fin_bank_rec_detail'),
    path('fin/tax/', views.fin_tax_list, name='fin_tax_list'),
    path('fin/tax/<int:filing_id>/', views.fin_tax_detail, name='fin_tax_detail'),
    path('it/', views.it_dashboard, name='it_dashboard'),
    path('it/tickets/', views.it_ticket_list, name='it_ticket_list'),
    path('it/tickets/<int:ticket_id>/', views.it_ticket_detail, name='it_ticket_detail'),
    path('it/assets/', views.it_asset_list, name='it_asset_list'),
    path('it/assets/<int:asset_id>/', views.it_asset_detail, name='it_asset_detail'),
    path('it/repairs/', views.it_repairs_list, name='it_repairs_list'),
    path('it/repairs/<int:repair_id>/', views.it_repairs_detail, name='it_repairs_detail'),
    path('it/software/', views.it_software_list, name='it_software_list'),
    path('it/software/<int:sw_id>/', views.it_software_detail, name='it_software_detail'),
    path('it/licenses/', views.it_license_list, name='it_license_list'),
    path('it/licenses/<int:license_id>/', views.it_license_detail, name='it_license_detail'),
    path('it/network/', views.it_network_list, name='it_network_list'),
    path('it/network/<int:device_id>/', views.it_network_detail, name='it_network_detail'),
    path('it/tasks/', views.it_task_list, name='it_task_list'),
    path('it/tasks/<int:task_id>/', views.it_task_detail, name='it_task_detail'),
    path('it/incidents/', views.it_incident_list, name='it_incident_list'),
    path('it/incidents/<int:incident_id>/', views.it_incident_detail, name='it_incident_detail'),
    # Fixed Asset Management
    path('assets/fixed/', views.fixed_asset_list, name='fixed_asset_list'),
    path('assets/fixed/<int:asset_id>/', views.fixed_asset_detail, name='fixed_asset_detail'),
    # Currency Management
    path('admin/currencies/', views.currency_list, name='currency_list'),
    # Approval Rule Management
    path('approval-rules/', views.approval_rule_list, name='approval_rule_list'),
    path('approval-rules/new/', views.approval_rule_new, name='approval_rule_new'),
    path('approval-rules/<int:rule_id>/', views.approval_rule_edit,
         name='approval_rule_edit'),
    # Webhook Subscription Management
    path('webhooks/', views.webhook_list, name='webhook_list'),
    path('webhooks/new/', views.webhook_new, name='webhook_new'),
    path('webhooks/<int:subscription_id>/', views.webhook_edit, name='webhook_edit'),
    path('legal/', views.legal_dashboard, name='legal_dashboard'),
    path('budget/', views.budget_dashboard, name='budget_dashboard'),
    path('risk/', views.risk_dashboard, name='risk_dashboard'),
    path('legal/contracts/', views.legal_contract_list, name='legal_contract_list'),
    path('legal/contracts/<int:contract_id>/', views.legal_contract_detail, name='legal_contract_detail'),
    path('legal/compliance/', views.legal_compliance_list, name='legal_compliance_list'),
    path('legal/compliance/<int:item_id>/', views.legal_compliance_detail, name='legal_compliance_detail'),
    path('legal/litigation/', views.legal_litigation_list, name='legal_litigation_list'),
    path('legal/litigation/<int:case_id>/', views.legal_litigation_detail, name='legal_litigation_detail'),
    path('mkt/', views.mkt_dashboard, name='mkt_dashboard'),
    path('mkt/campaigns/', views.mkt_campaign_list, name='mkt_campaign_list'),
    path('mkt/campaigns/<int:campaign_id>/', views.mkt_campaign_detail, name='mkt_campaign_detail'),
    path('mkt/leads/', views.mkt_lead_list, name='mkt_lead_list'),
    path('mkt/leads/<int:lead_id>/', views.mkt_lead_detail, name='mkt_lead_detail'),
    path('mkt/content/', views.mkt_content_list, name='mkt_content_list'),
    path('mkt/content/<int:item_id>/', views.mkt_content_detail, name='mkt_content_detail'),
    path('mkt/ads/', views.mkt_ad_list, name='mkt_ad_list'),
    path('mkt/ads/<int:ad_id>/', views.mkt_ad_detail, name='mkt_ad_detail'),
    path('mkt/research/', views.mkt_research_list, name='mkt_research_list'),
    path('mkt/research/<int:project_id>/', views.mkt_research_detail, name='mkt_research_detail'),
    path('mkt/analytics/', views.mkt_analytics, name='mkt_analytics'),
    path('purch/', views.purch_dashboard, name='purch_dashboard'),
    path('purch/contracts/', views.purch_contracts_list, name='purch_contracts_list'),
    path('purch/contracts/<int:contract_id>/', views.purch_contract_detail, name='purch_contract_detail'),
    path('purch/reports/', views.purch_reports_view, name='purch_reports_view'),
    path('pers/', views.pers_dashboard, name='pers_dashboard'),
    path('pers/depts/', views.pers_depts, name='pers_depts'),
    path('pers/reviews/', views.pers_reviews_list, name='pers_reviews_list'),
    path('pers/reviews/<int:review_id>/', views.pers_review_detail, name='pers_review_detail'),
    path('pers/training/', views.pers_training_list, name='pers_training_list'),
    path('pers/training/<int:training_id>/', views.pers_training_detail, name='pers_training_detail'),
    path('cs-dash/', views.cs_dashboard_view, name='cs_dashboard'),
    path('cs/returns/', views.cs_returns_list, name='cs_returns_list'),
    path('cs/returns/<int:return_id>/', views.cs_returns_detail, name='cs_returns_detail'),
    path('cs/kb/', views.cs_kb_list, name='cs_kb_list'),
    path('cs/kb/<int:article_id>/', views.cs_kb_detail, name='cs_kb_detail'),
    path('cs/surveys/', views.cs_surveys_list, name='cs_surveys_list'),
    path('cs/surveys/<int:survey_id>/', views.cs_surveys_detail, name='cs_surveys_detail'),
    # Mobile REST API  (/api/v1/…)
    path('api/v1/auth/login/',    api_views.api_login,    name='api_login'),
    path('api/v1/auth/logout/',   api_views.api_logout,   name='api_logout'),
    path('api/v1/auth/refresh/',  api_views.api_refresh,  name='api_refresh'),
    path('api/v1/auth/profile/',  api_views.api_profile,  name='api_profile'),
    path('api/v1/dashboard/',     api_views.api_dashboard, name='api_dashboard'),
    # Phase 5A — extended dashboards
    path('api/v1/dashboards/financial/',   api_views.api_financial_dashboard,  name='api_financial_dashboard'),
    path('api/v1/dashboards/production/',  api_views.api_production_dashboard, name='api_production_dashboard'),
    path('api/v1/dashboards/inventory/',   api_views.api_inventory_dashboard,  name='api_inventory_dashboard'),
    path('api/v1/time-clock/status/',    api_views.api_tc_status,    name='api_tc_status'),
    path('api/v1/time-clock/clock-in/',  api_views.api_tc_clock_in,  name='api_tc_clock_in'),
    path('api/v1/time-clock/clock-out/', api_views.api_tc_clock_out, name='api_tc_clock_out'),
    path('api/v1/time-clock/hours/',     api_views.api_tc_hours,     name='api_tc_hours'),
    path('api/v1/time-off/',      api_views.api_time_off, name='api_time_off'),
    path('api/v1/wo/',            api_views.api_wo_list,  name='api_wo_list'),
    path('api/v1/wo/<int:wo_id>/',          api_views.api_wo_detail,   name='api_wo_detail'),
    path('api/v1/wo/<int:wo_id>/status/',   api_views.api_wo_status,   name='api_wo_status'),
    # Phase 5C — WO operations (routing steps)
    path('api/v1/wo/<int:wo_id>/operations/',
         api_views.api_wo_operations, name='api_wo_operations'),
    path('api/v1/wo/<int:wo_id>/operations/<int:seq>/complete/',
         api_views.api_wo_operation_complete, name='api_wo_operation_complete'),
    path('api/v1/req/',                     api_views.api_req,           name='api_req'),
    path('api/v1/req/pending/',             api_views.api_req_pending,   name='api_req_pending'),
    path('api/v1/req/<int:req_id>/items/',  api_views.api_req_add_item,  name='api_req_add_item'),
    path('api/v1/req/<int:req_id>/submit/', api_views.api_req_submit,    name='api_req_submit'),
    path('api/v1/req/<int:req_id>/decide/', api_views.api_req_decide,    name='api_req_decide'),
    # Phase 5C — inventory, quality NCR, maintenance WOs
    path('api/v1/inventory/',              api_views.api_inventory_list,    name='api_inventory_list'),
    path('api/v1/inventory/receive/',      api_views.api_inventory_receive, name='api_inventory_receive'),
    path('api/v1/quality/ncr/',            api_views.api_ncr,               name='api_ncr'),
    path('api/v1/quality/ncr/<int:ncr_id>/', api_views.api_ncr_detail,     name='api_ncr_detail'),
    path('api/v1/maint/wo/',               api_views.api_maint_wo_list,     name='api_maint_wo_list'),
    path('api/v1/maint/wo/<int:wo_id>/',   api_views.api_maint_wo_detail,   name='api_maint_wo_detail'),
    path('api/v1/maint/wo/<int:wo_id>/complete/', api_views.api_maint_wo_complete, name='api_maint_wo_complete'),
    # Phase 6B — approval workflow
    path('api/v1/approvals/pending/',              api_views.api_workflow_pending, name='api_workflow_pending'),
    path('api/v1/approvals/steps/<int:step_id>/decide/', api_views.api_workflow_decide, name='api_workflow_decide'),
    # Phase 7A — lots, routing, costing
    path('api/v1/lots/',                           api_views.api_lot_list,         name='api_lot_list'),
    path('api/v1/lots/expiry/',                    api_views.api_lot_expiry,        name='api_lot_expiry'),
    path('api/v1/lots/<int:lot_id>/',              api_views.api_lot_detail,        name='api_lot_detail'),
    path('api/v1/lots/<int:lot_id>/status/',       api_views.api_lot_status,        name='api_lot_status'),
    path('api/v1/serials/',                        api_views.api_serial_list,       name='api_serial_list'),
    path('api/v1/serials/<int:serial_id>/status/', api_views.api_serial_status,     name='api_serial_status'),
    path('api/v1/workcenters/',                    api_views.api_workcenters,       name='api_workcenters'),
    path('api/v1/routing/<int:product_id>/',       api_views.api_product_routing,   name='api_product_routing'),
    path('api/v1/wo/<int:wo_id>/operations/<int:seq>/start/',
         api_views.api_wo_operation_start,               name='api_wo_operation_start'),
    path('api/v1/costs/<int:product_id>/',         api_views.api_product_cost,      name='api_product_cost'),
    path('api/v1/costs/<int:product_id>/roll/',    api_views.api_cost_roll,         name='api_cost_roll'),
    path('api/v1/costs/<int:product_id>/history/', api_views.api_cost_history,      name='api_cost_history'),
    path('api/v1/wo/<int:wo_id>/cost/',            api_views.api_wo_cost,           name='api_wo_cost'),
    path('api/v1/wo/<int:wo_id>/cost/compute/',    api_views.api_wo_cost_compute,   name='api_wo_cost_compute'),
    path('api/v1/gl-accounts/',                    api_views.api_gl_accounts,       name='api_gl_accounts'),
    # Barcode scan & label printing
    path('scan/', views.scan_home, name='scan_home'),
    path('scan/lookup/', views.scan_lookup, name='scan_lookup'),
    path('scan/receive/', views.receive_scan, name='receive_scan'),
    path('label/wo/<int:wo_id>/', views.label_wo, name='label_wo'),
    path('label/part/<int:product_id>/', views.label_part, name='label_part'),
    path('label/po/<int:po_id>/', views.label_po, name='label_po'),
    path('label/receiving/<int:po_id>/', views.label_receiving, name='label_receiving'),
    path('label/asset/<int:asset_id>/', views.label_asset, name='label_asset'),
    path('barcode/img/<path:code>/', views.barcode_img, name='barcode_img'),
    # Customer Self-Service Portal (P3-C)
    path('portal/register/', views.portal_register, name='portal_register'),
    path('portal/login/', views.portal_login, name='portal_login'),
    path('portal/logout/', views.portal_logout, name='portal_logout'),
    path('portal/', views.portal_home, name='portal_home'),
    path('portal/orders/', views.portal_orders, name='portal_orders'),
    path('portal/orders/<int:so_id>/', views.portal_order_detail, name='portal_order_detail'),
    path('portal/invoices/', views.portal_invoices, name='portal_invoices'),
    path('portal/invoices/<int:inv_id>/', views.portal_invoice_detail, name='portal_invoice_detail'),
    path('portal/invoices/<int:inv_id>/pdf/', views.portal_invoice_pdf, name='portal_invoice_pdf'),
    path('portal/invoices/<int:inv_id>/pay/', views.portal_invoice_pay, name='portal_invoice_pay'),
    path('portal/shipments/<int:shipment_id>/', views.portal_shipment_detail, name='portal_shipment_detail'),
    path('portal/shipments/<int:shipment_id>/packing-slip/',
         views.portal_packing_slip_pdf, name='portal_packing_slip_pdf'),
    path('portal/rma/', views.portal_rma_list, name='portal_rma_list'),
    path('portal/rma/new/', views.portal_rma_new, name='portal_rma_new'),
    path('portal/rma/<int:rma_id>/', views.portal_rma_detail, name='portal_rma_detail'),
    path('supplier-portal/register/', views.supplier_portal_register, name='supplier_portal_register'),
    path('supplier-portal/login/', views.supplier_portal_login, name='supplier_portal_login'),
    path('supplier-portal/logout/', views.supplier_portal_logout, name='supplier_portal_logout'),
    path('supplier-portal/', views.supplier_portal_home, name='supplier_portal_home'),
    path('supplier-portal/pos/', views.supplier_portal_pos, name='supplier_portal_pos'),
    path('supplier-portal/pos/<int:po_id>/', views.supplier_portal_po_detail, name='supplier_portal_po_detail'),
    path('supplier-portal/invoices/', views.supplier_portal_invoices, name='supplier_portal_invoices'),
    path('supplier-portal/invoices/new/', views.supplier_portal_invoice_new, name='supplier_portal_invoice_new'),
    path('supplier-portal/invoices/<int:inv_id>/', views.supplier_portal_invoice_detail,
         name='supplier_portal_invoice_detail'),
    path('supplier-portal/rfqs/', views.supplier_portal_rfqs, name='supplier_portal_rfqs'),
    path('supplier-portal/rfqs/<int:rfq_id>/', views.supplier_portal_rfq_detail, name='supplier_portal_rfq_detail'),
    path('ecommerce/connections/', views.ecommerce_connection_list, name='ecommerce_connection_list'),
    path('ecommerce/connections/new/', views.ecommerce_connection_new, name='ecommerce_connection_new'),
    path('ecommerce/connections/<int:connection_id>/', views.ecommerce_connection_detail,
         name='ecommerce_connection_detail'),
    path('ecommerce/webhook/<int:connection_id>/order/', views.ecommerce_order_webhook, name='ecommerce_order_webhook'),
    path('ecommerce/shipment/<int:shipment_id>/push/', views.ecommerce_shipment_push, name='ecommerce_shipment_push'),
    path('ecommerce/log/', views.ecommerce_sync_log_list, name='ecommerce_sync_log_list'),
    path('reports/builder/', views.report_builder_list, name='report_builder_list'),
    path('reports/builder/new/', views.report_builder_new, name='report_builder_new'),
    path('reports/builder/<int:report_id>/', views.report_builder_detail, name='report_builder_detail'),
    path('reports/builder/<int:report_id>/edit/', views.report_builder_edit, name='report_builder_edit'),
    path('reports/builder/<int:report_id>/csv/', views.report_builder_csv, name='report_builder_csv'),
    path('reports/builder/<int:report_id>/pdf/', views.report_builder_pdf, name='report_builder_pdf'),
    path('reports/builder/<int:report_id>/delete/', views.report_builder_delete, name='report_builder_delete'),
    path('carbon/<int:product_id>/', views.carbon_detail, name='carbon_detail'),
    path('carbon/wo/<int:wo_id>/', views.wo_carbon_detail, name='wo_carbon_detail'),
    path('carbon/workcenter/<int:wc_id>/', views.workcenter_carbon_factor, name='workcenter_carbon_factor'),
    path('esg/', views.esg_dashboard, name='esg_dashboard'),
    path('dept/<str:dept>/', views.generic_menu, name='dept_menu'),
    path('dept/<str:dept>/<path:subpath>/',
         views.generic_menu, name='submenu'),
]
