from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    path('forgot-password/', views.forgot_password, name='forgot_password'),
    path(
    'forgot-password/reset/',
    views.forgot_password_reset,
     name='forgot_password_reset'),
    path('change-password/', views.change_password, name='change_password'),
    path('user-roles/', views.user_roles, name='user_roles'),
    path('po/', views.po_list, name='po_list'),
    path('po/new/', views.po_new, name='po_new'),
    path('po/<int:po_id>/', views.po_detail, name='po_detail'),
    path('po/<int:po_id>/edit/', views.po_edit, name='po_edit'),
    path('po/<int:po_id>/items/add/', views.po_add_item, name='po_add_item'),
    path('po/<int:po_id>/items/remove/', views.po_remove_item,
         name='po_remove_item'),
    path('po/<int:po_id>/items/receive/', views.po_receive_item,
         name='po_receive_item'),
    path('po/<int:po_id>/status/', views.po_set_status, name='po_set_status'),
    path('reports/', views.reports_dashboard, name='reports_dashboard'),
    path('wo/', views.wo_list, name='wo_list'),
    path('wo/new/', views.wo_new, name='wo_new'),
    path('wo/<int:wo_id>/', views.wo_detail, name='wo_detail'),
    path('wo/<int:wo_id>/edit/', views.wo_edit, name='wo_edit'),
    path('wo/<int:wo_id>/materials/add/', views.wo_add_material,
         name='wo_add_material'),
    path('wo/<int:wo_id>/status/', views.wo_set_status, name='wo_set_status'),
    path('so/', views.so_list, name='so_list'),
    path('so/new/', views.so_new, name='so_new'),
    path('so/<int:so_id>/', views.so_detail, name='so_detail'),
    path('so/<int:so_id>/edit/', views.so_edit, name='so_edit'),
    path('so/<int:so_id>/items/add/', views.so_add_item, name='so_add_item'),
    path('so/<int:so_id>/items/remove/', views.so_remove_item,
         name='so_remove_item'),
    path('so/<int:so_id>/status/', views.so_set_status, name='so_set_status'),
    path('people/', views.people_list, name='people_list'),
    path('people/new/', views.people_new, name='people_new'),
    path('people/<int:person_id>/', views.people_detail, name='people_detail'),
    path('people/<int:person_id>/edit/', views.people_edit, name='people_edit'),
    path('time-off/', views.time_off_list, name='time_off_list'),
    path('time-off/new/', views.time_off_new, name='time_off_new'),
    path('time-off/<int:req_id>/', views.time_off_detail,
         name='time_off_detail'),
    path('time-clock/', views.time_clock_status, name='time_clock_status'),
    path('time-clock/hours/', views.time_clock_hours, name='time_clock_hours'),
    path('time-clock/attendance/', views.time_clock_attendance,
         name='time_clock_attendance'),
    path('time-clock/devices/', views.tc_device_list,
         name='tc_device_list'),
    path('time-clock/devices/new/', views.tc_device_new,
         name='tc_device_new'),
    path('time-clock/devices/<int:device_id>/', views.tc_device_detail,
         name='tc_device_detail'),
    path('time-clock/devices/<int:device_id>/poll/', views.tc_device_poll,
         name='tc_device_poll'),
    path('time-clock/devices/<int:device_id>/delete/', views.tc_device_delete,
         name='tc_device_delete'),
    path('audit/', views.audit_log, name='audit_log'),
    path('audit/<str:table_name>/<int:record_id>/',
         views.audit_record, name='audit_record'),
    path('bom/', views.bom_list, name='bom_list'),
    path('bom/<int:product_id>/', views.bom_detail, name='bom_detail'),
    path('bom/<int:product_id>/explode/', views.bom_explode, name='bom_explode'),
    path('mrp/', views.mrp_home, name='mrp_home'),
    path('mrp/run/', views.mrp_run, name='mrp_run'),
    path('mrp/plan/', views.mrp_plan, name='mrp_plan'),
    path('mrp/release/', views.mrp_release, name='mrp_release'),
    path('inventory/', views.inventory_list, name='inventory_list'),
    path('inventory/new/', views.inventory_new, name='inventory_new'),
    path('inventory/<int:product_id>/', views.inventory_detail,
         name='inventory_detail'),
    path('inventory/<int:product_id>/transaction/',
         views.inventory_transaction, name='inventory_transaction'),
    path('customers/', views.customer_list, name='customer_list'),
    path('customers/new/', views.customer_new, name='customer_new'),
    path('customers/<int:customer_id>/', views.customer_detail,
         name='customer_detail'),
    path('suppliers/', views.supplier_list, name='supplier_list'),
    path('suppliers/new/', views.supplier_new, name='supplier_new'),
    path('suppliers/<int:supplier_id>/', views.supplier_detail,
         name='supplier_detail'),
    path('cs/', views.cs_ticket_list, name='cs_ticket_list'),
    path('cs/new/', views.cs_ticket_new, name='cs_ticket_new'),
    path('cs/<int:ticket_id>/', views.cs_ticket_detail,
         name='cs_ticket_detail'),
    path('cs/escalations/', views.cs_escalations, name='cs_escalations'),
    path('cs/reports/', views.cs_reports, name='cs_reports'),
    path('cs/plans/', views.cs_plans, name='cs_plans'),
    path('maint/', views.maint_dashboard, name='maint_dashboard'),
    path('maint/wo/', views.maint_wo_list, name='maint_wo_list'),
    path('maint/wo/<int:wo_id>/', views.maint_wo_detail, name='maint_wo_detail'),
    path('maint/equipment/', views.maint_equipment_list,
         name='maint_equipment_list'),
    path('maint/equipment/<int:eq_id>/', views.maint_equipment_detail,
         name='maint_equipment_detail'),
    path('maint/schedule/', views.maint_schedule_list,
         name='maint_schedule_list'),
    path('maint/schedule/<int:sched_id>/', views.maint_schedule_detail,
         name='maint_schedule_detail'),
    path('maint/inspections/', views.maint_inspection_list,
         name='maint_inspection_list'),
    path('maint/inspections/<int:insp_id>/', views.maint_inspection_detail,
         name='maint_inspection_detail'),
    path('maint/downtime/', views.maint_downtime_list,
         name='maint_downtime_list'),
    path('maint/downtime/<int:dt_id>/', views.maint_downtime_detail,
         name='maint_downtime_detail'),
    path('maint/parts/', views.maint_parts_list, name='maint_parts_list'),
    path('maint/parts/<int:part_id>/', views.maint_part_detail,
         name='maint_part_detail'),
    path('maint/mechanics/', views.maint_mechanics_list,
         name='maint_mechanics_list'),
    path('maint/mechanics/<int:mech_id>/', views.maint_mechanic_detail,
         name='maint_mechanic_detail'),
    path('qa/', views.qa_dashboard, name='qa_dashboard'),
    path('qa/ncr/', views.qa_ncr_list, name='qa_ncr_list'),
    path('qa/ncr/<int:ncr_id>/', views.qa_ncr_detail, name='qa_ncr_detail'),
    path('qa/capa/', views.qa_capa_list, name='qa_capa_list'),
    path('qa/capa/<int:capa_id>/', views.qa_capa_detail, name='qa_capa_detail'),
    path('qa/audits/', views.qa_audit_list, name='qa_audit_list'),
    path('qa/audits/<int:audit_id>/', views.qa_audit_detail,
         name='qa_audit_detail'),
    path('qa/suppliers/', views.qa_supplier_list, name='qa_supplier_list'),
    path('qa/suppliers/<int:sq_id>/', views.qa_supplier_detail,
         name='qa_supplier_detail'),
    path('qa/inspections/', views.qa_inspection_list,
         name='qa_inspection_list'),
    path('qa/inspections/<int:insp_id>/', views.qa_inspection_detail,
         name='qa_inspection_detail'),
    path('periods/', views.periods, name='periods'),
    path('po/approvals/', views.po_approvals, name='po_approvals'),
    path('po/approvals/<int:approval_id>/approve/', views.po_approve, name='po_approve'),
    path('po/approvals/<int:approval_id>/reject/', views.po_reject, name='po_reject'),
    # Payroll
    path('payroll/', views.payroll_dashboard, name='payroll_dashboard'),
    path('payroll/pay-rates/', views.payroll_pay_rates, name='payroll_pay_rates'),
    path('payroll/deductions/', views.payroll_deductions, name='payroll_deductions'),
    path('payroll/history/', views.payroll_history, name='payroll_history'),
    path('payroll/history/<int:run_id>/', views.payroll_run_detail, name='payroll_run_detail'),
    path('payroll/stubs/<int:entry_id>/', views.payroll_stub_detail, name='payroll_stub_detail'),
    path('payroll/ytd/', views.payroll_ytd, name='payroll_ytd'),
    # Accounts Payable
    path('ap/', views.ap_list, name='ap_list'),
    path('ap/new/', views.ap_invoice_detail, name='ap_invoice_new'),
    path('ap/<int:inv_id>/', views.ap_invoice_detail, name='ap_invoice_detail'),
    # Accounts Receivable
    path('ar/', views.ar_list, name='ar_list'),
    path('ar/new/', views.ar_invoice_detail, name='ar_invoice_new'),
    path('ar/<int:inv_id>/', views.ar_invoice_detail, name='ar_invoice_detail'),
    # General Ledger
    path('gl/', views.gl_dashboard, name='gl_dashboard'),
    path('gl/accounts/', views.gl_accounts, name='gl_accounts'),
    path('gl/journals/', views.gl_journals, name='gl_journals'),
    path('gl/journals/new/', views.gl_journal_detail, name='gl_journal_new'),
    path('gl/journals/<int:journal_id>/', views.gl_journal_detail, name='gl_journal_detail'),
    path('gl/trial-balance/', views.gl_trial_balance, name='gl_trial_balance'),
    path('gl/income-statement/', views.gl_income_statement, name='gl_income_statement'),
    path('gl/balance-sheet/', views.gl_balance_sheet, name='gl_balance_sheet'),
    path('eng/', views.eng_dashboard, name='eng_dashboard'),
    path('eng/projects/', views.eng_projects, name='eng_projects'),
    path('eng/projects/new/', views.eng_project_detail, name='eng_project_new'),
    path('eng/projects/<int:project_id>/', views.eng_project_detail, name='eng_project_detail'),
    path('eng/ecrs/', views.eng_ecrs, name='eng_ecrs'),
    path('eng/ecrs/new/', views.eng_ecr_detail, name='eng_ecr_new'),
    path('eng/ecrs/<int:ecr_id>/', views.eng_ecr_detail, name='eng_ecr_detail'),
    path('eng/reports/', views.eng_reports_view, name='eng_reports'),
    path('sales/', views.sales_dashboard, name='sales_dashboard'),
    path('sales/orders/', views.sales_orders_list, name='sales_orders_list'),
    path('sales/orders/new/', views.sales_order_detail, name='sales_order_new'),
    path('sales/orders/<int:so_id>/', views.sales_order_detail, name='sales_order_detail'),
    path('sales/quotes/', views.sales_quotes, name='sales_quotes'),
    path('sales/targets/', views.sales_targets, name='sales_targets'),
    path('prod/', views.prod_dashboard, name='prod_dashboard'),
    path('fin/', views.fin_dashboard, name='fin_dashboard'),
    path('it/', views.it_dashboard, name='it_dashboard'),
    path('legal/', views.legal_dashboard, name='legal_dashboard'),
    path('legal/contracts/', views.legal_contract_list, name='legal_contract_list'),
    path('legal/contracts/<int:contract_id>/', views.legal_contract_detail, name='legal_contract_detail'),
    path('legal/compliance/', views.legal_compliance_list, name='legal_compliance_list'),
    path('legal/compliance/<int:item_id>/', views.legal_compliance_detail, name='legal_compliance_detail'),
    path('legal/litigation/', views.legal_litigation_list, name='legal_litigation_list'),
    path('legal/litigation/<int:case_id>/', views.legal_litigation_detail, name='legal_litigation_detail'),
    path('mkt/', views.mkt_dashboard, name='mkt_dashboard'),
    path('purch/', views.purch_dashboard, name='purch_dashboard'),
    path('pers/', views.pers_dashboard, name='pers_dashboard'),
    path('cs-dash/', views.cs_dashboard_view, name='cs_dashboard'),
    path('dept/<str:dept>/', views.generic_menu, name='dept_menu'),
    path('dept/<str:dept>/<path:subpath>/',
         views.generic_menu, name='submenu'),
    path(
    'run/<str:dept>/<path:subpath>/',
    views.run_script,
     name='run_script'),
]
