from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    path('forgot-password/', views.forgot_password, name='forgot_password'),
    path(
    'forgot-password/reset/',
    views.forgot_password_reset,
     name='forgot_password_reset'),
    path('change-password/', views.change_password, name='change_password'),
    path('user-roles/', views.user_roles, name='user_roles'),
    path('po/', views.po_list, name='po_list'),
    path('po/new/', views.po_new, name='po_new'),
    path('po/<int:po_id>/', views.po_detail, name='po_detail'),
    path('po/<int:po_id>/edit/', views.po_edit, name='po_edit'),
    path('po/<int:po_id>/items/add/', views.po_add_item, name='po_add_item'),
    path('po/<int:po_id>/items/remove/', views.po_remove_item,
         name='po_remove_item'),
    path('po/<int:po_id>/items/receive/', views.po_receive_item,
         name='po_receive_item'),
    path('po/<int:po_id>/status/', views.po_set_status, name='po_set_status'),
    path('reports/', views.reports_dashboard, name='reports_dashboard'),
    path('wo/', views.wo_list, name='wo_list'),
    path('wo/new/', views.wo_new, name='wo_new'),
    path('wo/<int:wo_id>/', views.wo_detail, name='wo_detail'),
    path('wo/<int:wo_id>/edit/', views.wo_edit, name='wo_edit'),
    path('wo/<int:wo_id>/materials/add/', views.wo_add_material,
         name='wo_add_material'),
    path('wo/<int:wo_id>/status/', views.wo_set_status, name='wo_set_status'),
    path('so/', views.so_list, name='so_list'),
    path('so/new/', views.so_new, name='so_new'),
    path('so/<int:so_id>/', views.so_detail, name='so_detail'),
    path('so/<int:so_id>/edit/', views.so_edit, name='so_edit'),
    path('so/<int:so_id>/items/add/', views.so_add_item, name='so_add_item'),
    path('so/<int:so_id>/items/remove/', views.so_remove_item,
         name='so_remove_item'),
    path('so/<int:so_id>/status/', views.so_set_status, name='so_set_status'),
    path('people/', views.people_list, name='people_list'),
    path('people/new/', views.people_new, name='people_new'),
    path('people/<int:person_id>/', views.people_detail, name='people_detail'),
    path('people/<int:person_id>/edit/', views.people_edit, name='people_edit'),
    path('time-off/', views.time_off_list, name='time_off_list'),
    path('time-off/new/', views.time_off_new, name='time_off_new'),
    path('time-off/<int:req_id>/', views.time_off_detail,
         name='time_off_detail'),
    path('time-clock/', views.time_clock_status, name='time_clock_status'),
    path('time-clock/hours/', views.time_clock_hours, name='time_clock_hours'),
    path('time-clock/attendance/', views.time_clock_attendance,
         name='time_clock_attendance'),
    path('time-clock/devices/', views.tc_device_list,
         name='tc_device_list'),
    path('time-clock/devices/new/', views.tc_device_new,
         name='tc_device_new'),
    path('time-clock/devices/<int:device_id>/', views.tc_device_detail,
         name='tc_device_detail'),
    path('time-clock/devices/<int:device_id>/poll/', views.tc_device_poll,
         name='tc_device_poll'),
    path('time-clock/devices/<int:device_id>/delete/', views.tc_device_delete,
         name='tc_device_delete'),
    path('audit/', views.audit_log, name='audit_log'),
    path('audit/<str:table_name>/<int:record_id>/',
         views.audit_record, name='audit_record'),
    path('bom/', views.bom_list, name='bom_list'),
    path('bom/<int:product_id>/', views.bom_detail, name='bom_detail'),
    path('bom/<int:product_id>/explode/', views.bom_explode, name='bom_explode'),
    path('mrp/', views.mrp_home, name='mrp_home'),
    path('mrp/run/', views.mrp_run, name='mrp_run'),
    path('mrp/plan/', views.mrp_plan, name='mrp_plan'),
    path('mrp/release/', views.mrp_release, name='mrp_release'),
    path('periods/', views.periods, name='periods'),
    path('po/approvals/', views.po_approvals, name='po_approvals'),
    path('po/approvals/<int:approval_id>/approve/', views.po_approve, name='po_approve'),
    path('po/approvals/<int:approval_id>/reject/', views.po_reject, name='po_reject'),
    path('dept/<str:dept>/', views.generic_menu, name='dept_menu'),
    path('dept/<str:dept>/<path:subpath>/',
         views.generic_menu, name='submenu'),
    path(
    'run/<str:dept>/<path:subpath>/',
    views.run_script,
     name='run_script'),
]
